### ISSUE TITLE
Ordering of column names in correlation matrix

### ISSUE THREAD

**Issue by sbrugman** [KaveIO/PhiK#1]
The `df.phik_matrix()` returns the correlation matrix with the column names ordered. Pandas keeps the order identical to the input (e.g. [`df.corr('pearson')`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.corr.html])). 

I would propose to preserve the order as given in the dataframe. It is a simple preprocessing step to sort the columns if desired, for reversing we need to get the mapping from the original dataframe etc. This also allows for easier comparison with correlation matrices produces by pandas.

**Comment by mbaak** [comment]
Will take a look.

**Comment by mbaak** [comment]
Thanks for the big cleanup Simon! ;-)

I've pushed phik v0.10.0 to pypi
