### ISSUE TITLE
NCORES Related Crash on Windows

### ISSUE THREAD

**Issue by IronFarm** [KaveIO/PhiK#10]
Hi,

It's not totally clear to me why but this line causes a crash on a Windows machine with 64 or more cores:
https://github.com/KaveIO/PhiK/blob/1ae2642579f5716a6b1f1c896c2271b741cbbcb7/python/phik/phik.py#L146

I believe it is related to this long-present bug in Python:
https://bugs.python.org/issue26903

I'd suggest allowing the NCORES to be overridden with an environment variable or manually decreasing the value when it is >=64 on a Windows machine.

Thanks

**Comment by mbaak** [comment]
Working on it.

**Comment by mbaak** [comment]
phik v0.9.12 should work again now on Windows machine with 64+ cores. Can you give it a try?

The number of cores used can now also be configured. Eg. for 4 cores:
import phik.config
phik.config.ncores = 4

... before you call phik.
