### ISSUE TITLE
Publish sdist to PyPI along with bdist_wheel

### ISSUE THREAD

**Issue by johnsushant** [KaveIO/PhiK#16]
Hi,

Would it be possible to have the sdist also published to PyPI along with the binary wheel? Many organizations have restrictions on being able to directly use binary wheels. It would be a massive help if a source distribution could also be published.

**Comment by johnsushant** [comment]
@mbaak Hey, can you please help with this?

@sbrugman said that you publish these packages to PyPI so you should be able to do this.

**Comment by mbaak** [comment]
@johnsushant Yes I can do this. I didn't get around to it yet. Let me pick it up this weekend.

**Comment by johnsushant** [comment]
@mbaak Hey, did you manage to take a look at this?

**Comment by mbaak** [comment]
Hi, I shall have it later today.

**Comment by mbaak** [comment]
@johnsushant 
Done! 
pip install phik==0.11.0
should install from the sdist.
Let me know if you experience any issues. If not I'll close the this issue.

**Comment by johnsushant** [comment]
@mbaak That worked perfectly. Thank you!
