### ISSUE TITLE
Open question on https://stats.stackexchange.com

### ISSUE THREAD

**Issue by bm765** [KaveIO/PhiK#23]
Hi,

thanks for bringing this library to the public! :-)

There is presently an unanswered question regarding phi_k in the stackexchange world.

With this issue, I just would like to bring your attention to it:

https://stats.stackexchange.com/questions/497742/making-sense-of-the-phi-k-correlation-coefficient

Thanks for having a look at it.

**Comment by mbaak** [comment]
Thanks for bringing this to our attention! I've posted a response and will follow up.
