### ISSUE TITLE
formatting

### ISSUE THREAD

**Issue by monocot** [KaveIO/PhiK#27]
Are there spacing formatting options for the heatmaps of the correlation report? I've set it to save to a pdf to try and have better viz, but:
report.correlation_report(df, significance_threshold=3, correlation_threshold=0.5, pdf_file_name='test.pdf')

resulting in squished up heatmaps. Expanding the zoom feature on the pdf is not working, so I was hoping there were some optimization options i'm missing in the tutorials :) 

![image](https://user-images.githubusercontent.com/37449728/130528674-9f0add24-9452-443f-9a46-8bcabdef41ba.png)

**Comment by mbaak** [comment]
Hello, 
The function correlation_report() does not have this functionality, but the underlying function plot_correlation_matrix() does, namely through the option: fontsize_factor. For example, try setting it to 0.5. 
I'm happy to add this in a future release, but for now I would suggest to simply call plot_correlation_matrix() instead. See the tutorial for an example.
Hope this works for you!
