### ISSUE TITLE
Distance metric in UMAP

### ISSUE THREAD

**Issue by gokceneraslan** [KaveIO/PhiK#3]
It would be interesting to see PhiK as a distance metric in UMAP (see https://github.com/lmcinnes/umap/issues/319). However, it requires a concise numba-enabled implementation in [distances.py](https://github.com/lmcinnes/umap/blob/master/umap/distances.py#L321)

**Comment by mbaak** [comment]
In distances.py, you can add a 'phik' function that call the function below, which accepts to arrays as input:
https://github.com/KaveIO/PhiK/blob/master/python/phik/phik.py#L233

**Comment by mbaak** [comment]
Thanks for the suggestion, but I'm afraid I don't have time to implement phi_k in umap's distances.py (however cool umap may be). They can use this library though! Will close this issue now.
