### ISSUE TITLE
Publish wheels for python 3.10

### ISSUE THREAD

**Issue by wwuck** [KaveIO/PhiK#32]
Can we please get phik updated for compatibility with python 3.10?  Are there any code changes required or can I just submit a PR to update the github workflows?

**Comment by RUrlus** [comment]
Hi @wwuck, thanks for the PR. It looks like there are no issues with Python 3.10. However, the latest run showed an issue with Pillow and Python 3.6 for the Wheels pipeline which blocks the merge.
When #35 is fixed we can merge in the PR
