### ISSUE TITLE
Drop support for Python 3.6 as it's past EOL

### ISSUE THREAD

**Issue by RUrlus** [KaveIO/PhiK#35]
The 3.6 wheel pipeline is failing on Ubuntu as Pillow cannot be installed.
Pillow no longer provides wheels for 3.6 and the CI-Buildwheels image doesn't ship with zlib which causes the error: `The headers or library files could not be found for zlib,  a required dependency when compiling Pillow from source.`.

Python 3.6 end-of-life data was 23 Dec 2021 and major packages are no longer supporting it in their latest releases.
@mbaak What do you think about dropping support for Python 3.6

**Comment by mbaak** [comment]
@RUrlus Okay, let's drop support for Python 3.6.
