### ISSUE TITLE
global_phik interpretation and range

### ISSUE THREAD

**Issue by tgrandje** [KaveIO/PhiK#37]
(First, thanks very much for this library.)

I'm having some trouble using the phik.global_phik. The [source code](https://github.com/KaveIO/PhiK/blob/bf9f3e7938d16437ff9b398a33042b719c91f8f1/phik/phik.py#L327) states that coefficients values are between 0 and 1.

I'm currently working with a small dataset which returns lots of coefficients outside this range (I get a 1.6 for instance).
Some exceptions are also encountered (due to the (1 - 1/ V[i][i]*Vinv[i][i]) being sometimes negative).

So two questions : 

- is this behaviour expected (my math level is not what it used to be, sorry for the "open" question)?
- what could trigger a negative (intermediate) coefficient? A feature definitively not able to be modelised by other values? (Btw, I've used the "quantile" option to be sure to have enough binned values in each category)

If needed, I can try to attach a dummy dataset (I'll just have to ensure anonymity first) ; but as this is more of a general question, this may not be needed...

Whatever the explanations, maybe the docstring could be enhanced with those.
Thanks in advance

**Comment by mbaak** [comment]
Hello, thanks for pointing this out. 
As it happens someone else contacted me about global_phik last week with the same issue. 
I hadn't experienced this myself before. Thinking more about, I think you've stumbled on a real issue, 
and I realize now g_k is probably not properly defined for the phi_k correlation matrix. 
I will look into this some more. In the meantime I will add a warning about the usage of g_k and update the docstring. 

Let me try to explain below: 
The concept of  global correlation comes from Pearson's correlation matrix, and strictly speaking holds only for multivariate normal distributions:

g_k = sqrt( 1 - [(C^{-1})_{kk}]^{-1}  )

where C is the corresponding Pearson correlation matrix. g_k is effectively a quantity summarizing of how strong one variable is correlated to all others. When we implemented this for phi_k we thought we could use the same formula, simply inserting the phi_k correlation matrix in the formula. 

A straight-forward add-on, essentially, after phi_k was obtained, we didn't spend too much time on g_k for the publication.
I realize now that the assumptions behind using g_k are probably invalid, causing that g_k is not between 0 and 1 when using the phi_k correlation matrix as input. (Although I'm not sure if it's the assumption of multivariate normal distributions, the supposed linearity of the sum of (categorical) features, or the fact that Pearson's correlation has a direction and phi_k has not. I need to think more about this.)

Most people use phi_k and not many people use g_k, from what I've seen. The usage of phi_k, significance, and outlier values is fine, we've studied those extensively, but g_k is a concept carried over from multivariate normal distributions that apparently does not properly translate to phi_k.

[That said, when the phi_k correlations to the other correlations are strong, one should expect the global correlation to be large (close to 1).  The bottom line is there is not very much extra information obtained from it that is not in the actual correlation matrix.]

**Comment by mbaak** [comment]
I think that g_k can still an interesting summary variable, but should be considered as an indicator for total correlation, not as a super informative value. And provided of course the caveats are properly mentioned.

**Comment by tgrandje** [comment]
Ok, thanks for the explanations.

Don't worry I was not about to ditch g_k, it is still an asset! I'm for now using it to ditch modelisations process beforehand when the value is to low.

In my case, the problem might have it's source from the data. Those are pollutant emissions from industries in France (send by those industries to the state agencies). I've actually seen many mistakes in those (for instance, sometimes, there are errors on the units) which may very well end up in dataset distributions not beeing normal (even after binning the data) ; I'll try to control this. 
There are no categorical data used here (I'm trying to use high-frequencies pollutants to interpolate low-frequencies pollutants).

Do you think a sample dataset would help you figure what is going on ? Or do you have it already (from that other source) ?

When you say "close to 1", do you mean that a 1.6 value is as "bad" as a .4 value ?

**Comment by mbaak** [comment]
I've used g_k myself in the past to get quick & dirty insights on whether one variable can be modelled in terms of the rest. If the value is close to zero, that's a good hint the answer is probably no. And if close to 1 there's a good chance it can be done. 
In that sense 1.6 is probably a "good" value (in terms of modelling), and 0.4 is not. A quick look at the actual correlation matrix will probably confirm that first has many high correlations, and the latter has not.
(Btw, I will probably add a line now to cap the values.)

**Comment by mbaak** [comment]
Btw unlike Pearson, phi_k should be relatively robust against outlier datapoints, e.g from having the wrong unit.

**Comment by tgrandje** [comment]
Good point, I'll check it. (And that was what I thought at first about outliers, but I may have too many wrong data; you'd be amazed...); I'll try to get some more insights.

About the cap value, I think I can do that easily ; I'll submit a pull requests if you want ?

**Comment by mbaak** [comment]
Ok!

**Comment by tgrandje** [comment]
I was wondering if I should also set a floor value at zero ? That would only be used when the (1 - 1/ V[i][i]*Vinv[i][i]) is negative. (Even if I haven't figure the whole math behind the machine, I don't think that would be a mistake as you are using the root function.) That way the docstring remains accurate (until you have time to figure a better way to handle this behaviour)...

_(I have also encountered a global malfunction on the inv() function which in turn resulted to Vinv beeing an array of NaNs. I seem to remember it was linked to me setting an wrong "binning" configuration (the units errors I was speaking of : turns out if you bin your data with quantile set to False and you have "enough" outliers, you will get empty bins...). Of course you don't want to set the result to zero in that case...)_

**Comment by mbaak** [comment]
Sure, capping it on both ends makes sense.

Rows or columns with only zero entries in the contingency matrix are automatically removed, so that cannot be an issue.
But I imagine it can happen that the correlation matrix is - somehow - not invertible. There is no check against that currently, and it would make sense to add it.

**Comment by mbaak** [comment]
Hey @tgrandje if you're not working on this yet then let me pick this up. (I want to change the doc string as well.)

**Comment by tgrandje** [comment]
Hello @mbaak  Sorry, I have been delayed (covid cluster at home since my last question in fact...). I'm almost done, I'll let you know shortly.
