### ISSUE TITLE
CMake error when building dev version

### ISSUE THREAD

**Issue by wwuck** [KaveIO/PhiK#55]
I'm getting a CMake error when trying to build a dev version.

I set `DEV = True` in `setup.py` and run `python3 -m build --wheel`.

The build fails with this error:
```
CMake Error at CMakeLists.txt:3 (PROJECT):
  VERSION "0.12.2.dev" format invalid.
```

**Comment by RUrlus** [comment]
thanks for reporting, fixed in master
