### ISSUE TITLE
Pass figsize as parameters in `report.correlation_report`

### ISSUE THREAD

**Issue by flacle** [KaveIO/PhiK#58]
When having a lot of dimensions to analyze, the default figure sizes squeeze the labels (tested with SVG output). One option is to pass the figure sizes as parameters. You can then manually change the size of the correlation matrix, significance matrix, etc.

**Comment by mbaak** [comment]
Thanks for the suggestion, I will look into it.

**Comment by mbaak** [comment]
Better late than never :-)

This functionality has been added to PR 
https://github.com/KaveIO/PhiK/pull/84/files
and will be available in the next patch release (later this week).
