### ISSUE TITLE
Suggestion for handling datetime columns

### ISSUE THREAD

**Issue by jkleint** [KaveIO/PhiK#7]
Hello again,

I'd like to run PhiK on a DataFrame containing datetime columns, treating them as interval variables, but they are not recognized as such:

```
dates = pd.DataFrame({
    'x': np.linspace(0, 1, 20), 
    'date': pd.date_range('2000-01-01', '2000-01-20')
})
dates.phik_matrix()
```
```
interval_cols not set, guessing: ['x']
```

When I try to set them as intervals, it crashes.

```
dates.phik_matrix(interval_cols=['x', 'date'])
```
```
TypeError: cannot astype a datetimelike from [datetime64[ns]] to [float64]
```

An easy way to handle this is to have `phik_matrix()` find date columns with `pd.select_dtypes()` or `pd.api.types.is_datetime64_any_dtype()` and convert them to (floating point) seconds since the epoch, then treat them as intervals.

```
dates = pd.DataFrame({
    'x': np.linspace(0, 1, 20), 
    'date': (pd.date_range('2000-01-01', '2000-01-20') - pd.Timestamp("1970-01-01")) / pd.Timedelta('1s')
})
```

Thanks again!

**Comment by mbaak** [comment]
Indeed this can be done pretty easily. I will take a look ...

**Comment by mbaak** [comment]
I've considered it, but have decided to keep the functionality as is, ie. by default we only accept normal variables for the calculation of phik. The main reason is b/c it's easy to change datetime objects to numbers (see example below), in which case they are of course picked up. 

The second reason is that how you convert datetime to a number / bin them is often use-case specific. For example, when you're interested in months of the year, you'll need to do something specific. Same if you want to bin by weeks and those weeks should start on Mondays, etc. 

df['date] = df['date'].apply(to_ns)

def to_ns(x):
    return pd.to_datetime(x).value

**Comment by jkleint** [comment]
For users, it's even easier if the library handles it.  :)

So you feel that crashing is preferable to a sensible default?  Since dates are pretty common in business-database-type dataframes, it seems like we'd want to provide a nice out-of-the-box experience for first-timers, rather than a crash.

In the reasonable case that your datetime columns are of roughly the same scale, it definitely makes sense to convert them to time-since-epoch scalars.  I would argue that this is by far the most common case, we could easily handle it, and only if you need something different should we make you do the work of manual conversion.

**Comment by mbaak** [comment]
Ok, I'll have another look.
