### ISSUE TITLE
Is Pandas dependency a must?

### ISSUE THREAD

**Issue by andreagalloni92** [KaveIO/PhiK#70]
Hi there, 

I have a question, is it possible to use this correlation coefficient library without pandas (such as only np.array?)? Any interest to get into that direcition?

Thanks and all the best.

**Comment by mbaak** [comment]
Hello, thanks for bringing this up. 
At the moment pandas is a dependency, although technically it can be removed in a relatively straight-forward way. This issue also came up ~one year ago, and at the time we decided against making it optional b/c that might break some other packages. 
That said, we have a plan to migrate phik to scipy (we're collecting citations and waiting for the right moment), and at that point make it accepts arrays only. Then we will make the change. So, a bit more patience I'm afraid :)

**Comment by andreagalloni92** [comment]
Clear, Thanks a lot!
