### ISSUE TITLE
Update links to notebooks

### ISSUE THREAD

**Issue by adrianari** [KaveIO/PhiK#72]
The example notebooks are referenced wrongly. In the example of the basic notebook, https://phik.readthedocs.io/en/latest/tutorials.html points to https://nbviewer.org/github/kaveio/phik/blob/master/python/phik/notebooks/phik_tutorial_basic.ipynb

Correct link would however be: https://nbviewer.org/github/KaveIO/PhiK/blob/master/phik/notebooks/phik_tutorial_basic.ipynb

Please check the according markdown.

**Comment by mbaak** [comment]
Thanks for letting us know, I will fix it!
