### ISSUE TITLE
Support for PySpark

### ISSUE THREAD

**Issue by nbernini** [KaveIO/PhiK#8]
Is there any roadmap to be able to run this library on PySpark?  We run this library on data frames with thousands of columns and the run time is very slow.

**Comment by mbaak** [comment]
I'm curious, how do you run it exactly? 

I do see a "logical" / straight-forward way to make this run with pyspark. phik needs a contingency table per variable-pair. Creating those can be easily done with pyspark and parallelized. I happen to have a bit of code that can do this that will be open-sourced soon. And I'm happy to try this then, in a month time or so. I suggest you ping me then, ok?

**Comment by mbaak** [comment]
I've committed v0.9.11 of the phik library, which contains an example of how to calculate the phik correlation matrix parallellized, starting from a spark dataframe.

See the example here:
https://nbviewer.jupyter.org/github/kaveio/phik/blob/master/python/phik/notebooks/phik_tutorial_spark.ipynb

The example consists of two steps. 1. Obtain the 2d contingency tables for all selected variable pairs. (To make these we use the popmon package.) 2. Calculate the Phi_K value for each variable pair from its contingency table. In the example both steps are done with spark. 

From what you seem to want, step 2 is the most important step. Concerning step 1, the popmon package will be open-sourced soon, but relies on the spark histogrammar package. So as long as you can create the 2d histograms for all variable pairs yourself in an alternate way, this example will work already. See for examples:
https://github.com/histogrammar/histogrammar-docs/tree/master/tutorials/scala-spark

Or wait a few weeks until popmon is open-sourced. I'll keep this thread open until then.

**Comment by nbernini** [comment]
@mbaak Thanks for this.  I'll wait until this popmon is open sourced and then test our the notebook example

**Comment by mbaak** [comment]
@nbernini popmon has now been open-sourced. Do "pip install popmon" to install it. 
Then you should be able to run the spark example.

**Comment by nbernini** [comment]
@mbaak Thanks for this.  Unfortunately, our spark instance is setup for python2.7 (oversight on my ned). I'll work w/ my DEV team to get us on python3X and perform testing after that.

**Comment by mbaak** [comment]
Good luck!
