### ISSUE TITLE
phi_k error with Polars DataFrame

### ISSUE THREAD

**Issue by Vla495** [KaveIO/PhiK#96]
Hi! When I add a Polars DataFrame to phik_matrix, I encounter an error: AttributeError: 'DataFrame' object has no attribute 'phik_matrix'. The steps I followed are outlined below. The Polars team recommended that I reach out to you.

It would be great if Polars DataFrames were supported by phik. Could you please consider implementing compatibility for multiple types of DataFrames as input? - https://github.com/narwhals-dev/narwhals

------------------------

```
import phik

#Assigning each variable to a type. phik also automatically outputs variable types, it is not recommended to assign the type yourself

data_types = {'administrative':'ordinal'
                      ,'administrative_duration':'interval'
                      ,'informational':'ordinal'
                      ,'informational_duration':'interval'
                      ,'productrelated':'ordinal'
                      ,'productrelated_duration':'interval'
                      ,'bouncerates':'ordinal'
                      ,'exitrates':'interval'
                      ,'pagevalues':'interval'
                      ,'specialday':'ordinal'
                      ,'month':'ordinal'
                      ,'visitortype':'categorical'
                      ,'weekend':'ordinal'
                      ,'revenue':'ordinal'
                      }

#Since interval type variables must be added to calculate phik, a list of interval variables is created.

interval_cols_pl = [col for col, v in data_types.items() if v=='interval' and col in df_pl.columns]

#columns DataFrame

pl_all_columns = list(df_pl.columns)

#Correlation matrix

corrilations = df_pl[pl_all_columns].phik_matrix(interval_cols = interval_cols_pl)
```
-----------------------------------

Log output

The phi_k library does not accept the polaris DataFrame. an error occurs when transmitting data
```
AttributeError                            Traceback (most recent call last)
Cell In[88], line 2
      1 # Матрица корреляции
----> 2 corrilations = df_pl[pl_all_columns].phik_matrix(interval_cols = interval_cols_pl)

AttributeError: 'DataFrame' object has no attribute 'phik_matrix'
```

**Comment by RUrlus** [comment]
Hi @Vla495 the package doesn't support Polars and adding it is a non-trivial exercise part of the backend assumes that the underlying data structure is a NumPy array (as is the case with Pandas DataFrames).

If there is sufficient interest we may consider adopting something like narwals.
Of course a PR is always welcome

**Comment by mbaak** [comment]
Hello @Vla495, indeed as @RUrlus noted it is not a trivial exercise.
However phik can be easily calculated from a 2d histogram of two variables (= contingency table) , expressed as a numpy array. Here are some tips if you happen to be inspired :)

See here to calculate phik from a 2d histogram:
https://github.com/KaveIO/PhiK/blob/master/phik/phik.py#L79

This notebook demonstrates how to calculate a phik_matrix for a spark dataframe:
https://github.com/KaveIO/PhiK/blob/master/phik/notebooks/phik_tutorial_spark.ipynb
which calls:
https://github.com/KaveIO/PhiK/blob/master/phik/phik.py#L35

and does essentially that:
1. create 2d histograms.
2. loop over them, calculate the phi for each one,
3. fill the phik matrix.

**Comment by Vla495** [comment]
Hello @mbaak , Hi @RUrlus ! Thank you for the suggestion and recommendations - it’s always helpful to explore alternative ways to solve a problem!
I found a solution by converting the Polars DataFrame to pandas using the df_pl.to_pandas() method.
